### ISSUE TITLE
RoadManager.getRoad null pointer exception

### ISSUE THREAD

**Issue by KaizenSolutions** [MKergall/osmbonuspack#120]
Hi,
I have followed the Tutoriel_1 but I can create a Route with the method getRoad()

Here the code in my onCreate method of my activity : 
           
 // Create the route
RoadManager roadManager = new OSRMRoadManager();  

ArrayList<GeoPoint> aWps = new ArrayList<>();
aWps.add(mOwnLocation);
aWps.add(mTgtLocation);
            
Road road = roadManager.getRoad(aWps); // THROW NULL POINTER EXCEPTION

Caused by: java.lang.NullPointerException
at org.osmdroid.bonuspack.routing.RoadManager.geoPointAsString(RoadManager.java:42)
at org.osmdroid.bonuspack.routing.OSRMRoadManager.getUrl(OSRMRoadManager.java:191)
at org.osmdroid.bonuspack.routing.OSRMRoadManager.getRoad(OSRMRoadManager.java:199)

I have the last versions of osmdroid and osmbonuspack in my libs folder : 
libs/osmbonuspack_v5.1.jar
libs/osmdroid-android-4.3.jar

I have tried to put this code in a Asynctask, I get the same issue.

Can somebody help me ?

Thanks
Léo

**Comment by KaizenSolutions** [comment]
Ok, it works when I put 2 location manually (mOwnLocation and mTgtLocation).

The issue was that mOwnLocation (the GPS location) was null.
