### ISSUE TITLE
The problem upon display of big kml (more than 1 000 polygons, more than 5 Mb) 

### ISSUE THREAD

**Issue by gagarinn** [MKergall/osmbonuspack#134]
Hi! I appreciate your assistance. I have issues upon the display of kml with more than 1 000 fields. Sometimes I  get an error when opening file:     FATAL EXCEPTION: main java.lang.OutOfMemoryError
            at java.util.concurrent.CopyOnWriteArrayList.add(CopyOnWriteArrayList.java:275)
            at org.osmdroid.views.overlay.OverlayManager.add(OverlayManager.java:42)
            at org.osmdroid.views.overlay.OverlayManager.add(OverlayManager.java:19)
            at java.util.AbstractList.add(AbstractList.java:425)
            at org.osmdroid.bonuspack.overlays.FolderOverlay.add(FolderOverlay.java:54)
            at org.osmdroid.bonuspack.kml.KmlFolder.buildOverlay(KmlFolder.java:161)
            at org.osmdroid.bonuspack.kml.KmlFolder.buildOverlay(KmlFolder.java:160)
            at com.osmnavigator.MapActivity.updateUIWithKml(MapActivity.java:1183)
            at com.osmnavigator.MapActivity$KmlLoadingTask.onPostExecute(MapActivity.java:1127)
            at com.osmnavigator.MapActivity$KmlLoadingTask.onPostExecute(MapActivity.java:1090)
            at android.os.AsyncTask.finish(AsyncTask.java:631)
            at android.os.AsyncTask.access$600(AsyncTask.java:177)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:175)
            at android.app.ActivityThread.main(ActivityThread.java:5279)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)

 If the file is opened without errors it works very slowly and I have in logcat: 
06-26 16:50:50.644      789-837/? E/o*.o*.t*.t*.BitmapTile*﹕ OutOfMemoryError loading bitmap: /storage/emulated/0/osmdroid/tiles/Mapnik/11/1247/695.png.tile
06-26 16:50:50.644      789-835/? E/o*.o*.t*.t*.BitmapTile*﹕ OutOfMemoryError loading bitmap: /storage/emulated/0/osmdroid/tiles/Mapnik/11/1248/695.png.tile
06-26 16:50:51.082      789-988/? E/dalvikvm﹕ adjustAdaptiveCoef max=8388608, min=2097152, ut=256
06-26 16:50:51.480      789-837/? E/dalvikvm﹕ adjustAdaptiveCoef max=8388608, min=2097152, ut=256
06-26 16:50:51.824      789-789/? E/dalvikvm﹕ adjustAdaptiveCoef max=8388608, min=2097152, ut=256
06-26 16:50:51.824      789-789/? E/dalvikvm-heap﹕ Out of memory on a 262160-byte allocation.
06-26 16:50:51.847      789-789/? E/o*.o*.t*.MapTileProvid*﹕ OutOfMemoryError rescaling cache
06-26 16:50:52.261      789-835/? E/dalvikvm﹕ adjustAdaptiveCoef max=8388608, min=2097152, ut=256
06-26 16:50:52.582      789-838/? E/dalvikvm﹕ adjustAdaptiveCoef max=8388608, min=2097152, ut=256
06-26 16:50:52.582      789-838/? E/dalvikvm-heap﹕ Out of memory on a 262160-byte allocation.
06-26 16:50:52.918      789-830/? E/dalvikvm﹕ adjustAdaptiveCoef max=8388608, min=2097152, ut=256
06-26 16:50:52.918      789-830/? E/dalvikvm-heap﹕ Out of memory on a 262160-byte allocation.
06-26 16:50:53.261      789-847/? E/dalvikvm﹕ adjustAdaptiveCoef max=8388608, min=2097152, ut=256
06-26 16:50:53.261      789-847/? E/dalvikvm-heap﹕ Out of memory on a 262160-byte allocation.
06-26 16:50:53.621      789-833/? E/dalvikvm﹕ adjustAdaptiveCoef max=8388608, min=2097152, ut=256
06-26 16:50:53.621      789-833/? E/dalvikvm-heap﹕ Out of memory on a 262160-byte allocation.
06-26 16:50:54.043      789-840/? E/dalvikvm﹕ adjustAdaptiveCoef max=8388608, min=2097152, ut=256
06-26 16:50:54.043      789-840/? E/dalvikvm-heap﹕ Out of memory on a 262160-byte allocation.
06-26 16:50:54.472      789-991/? E/dalvikvm﹕ adjustAdaptiveCoef max=8388608, min=2097152, ut=256
06-26 16:50:54.480      789-991/? E/dalvikvm-heap﹕ Out of memory on a 262160-byte allocation.
06-26 16:50:54.582      484-778/? E/Watchdog﹕ !@Sync 4060 …

When I want to clear there is an error: 
E/AndroidRuntime﹕ FATAL EXCEPTION: main
    android.view.InflateException: Binary XML file line #26: Error inflating class <unknown> ...
and 
E/ActivityThread﹕ Service com.android.exchange.ExchangeService has leaked ServiceConnection com.android.emailcommon.service.ServiceProxy$ProxyConnection@41c9cd30 that was originally bound here
    android.app.ServiceConnectionLeaked: Service com.android.exchange.ExchangeService has leaked ServiceConnection com.android.emailcommon.service.ServiceProxy$ProxyConnection@41c9cd30 that was originally bound here

Can you help me?

**Comment by MKergall** [comment]
Did you read this: https://github.com/MKergall/osmbonuspack/wiki/KML#limits

**Comment by gagarinn** [comment]
Thank you very much! So much better!

**Comment by MKergall** [comment]
Glad to see that people are pushing the lib to its limits :-)
Do we close this issue?

**Comment by gagarinn** [comment]
Yes thank you!
