### ISSUE TITLE
Load KML as overlay: error in buildOverlay

### ISSUE THREAD

**Issue by blanml** [MKergall/osmbonuspack#156]
Hi,

I'm using osmDroid (osmdroid-android-4.3.jar) with bonuspack (osmbonuspack_v5.3.aar) in my Android app. I have to overlay a KML file over the mapview (osm).  
My code is:

-------------------------------------------------------------------------------------------------------------------------------
OnCreate function:

    protected MapView mapOSM;
    protected MapController mapControl;

    Geocoder geoCoder;
    MyLocationOverlay myLocationOverlay = null;
    public static KmlDocument mKmlDocument; //made static to pass between activities
    protected FolderOverlay mKmlOverlay; //root container of overlays from KML reading

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_maps);

        mapOSM = (MapView) findViewById(R.id.mapOSM);
        mapOSM.setTileSource(TileSourceFactory.MAPNIK);
        mapOSM.setBuiltInZoomControls(false); //quita los botones de zoom de la pantalla
        mapOSM.setMultiTouchControls(true);
        mapOSM.setEnabled(true);
        mapOSM.setClickable(true);

        mapControl = (MapController) mapOSM.getController();
        mapControl.setZoom(13);
        GeoPoint myLocation = new GeoPoint(40.46560773896929, -3.6887799453731081);
        mapControl.setCenter(myLocation);

        myLocationOverlay = new MyLocationOverlay(this, mapOSM);
        mapOSM.getOverlays().add(myLocationOverlay);
        mapOSM.invalidate();

        String url = "http://mapsengine.google.com/map/kml?forcekml=1&mid=z6IJfj90QEd4.kcfEKhi8r5LQ";
        mKmlDocument = new KmlDocument();
        mKmlOverlay = null;
        putKMLAsync(url);

Functions Async:

    private class putKML extends AsyncTask<String, Void, Boolean> {
        @Override
        protected Boolean doInBackground(String... url) {
            boolean ok = false;
            ok = mKmlDocument.parseKMLUrl(url[0]);
            return ok;
        }

        @Override
        protected void onPostExecute(Boolean ok) {
            //super.onPostExecute(ok);
            updateKML();
        }
    }

    private void putKMLAsync(String url) {
        new putKML().execute(url);
    }

    private void updateKML(){
        if (mKmlOverlay != null){
            mKmlOverlay.closeAllInfoWindows();
            mapOSM.getOverlays().remove(mKmlOverlay);
        }
        mKmlOverlay = (FolderOverlay) mKmlDocument.mKmlRoot.buildOverlay(mapOSM, null, null, mKmlDocument);
        mapOSM.getOverlays().add(mKmlOverlay);
        mapOSM.invalidate();
    }

-------------------------------------------------------------------------------------------------------------------------------

My problem is: buildOverlay gives me an error in execution and I don't know why. My code compiles without any error.
I would greatly appreciate if you could give me a solution. Thank you in advance.

**Comment by MKergall** [comment]
Please provide the stack trace of the error.

**Comment by blanml** [comment]
This is the stack trace of the error. Thank you for answering so quickly.



10-02 14:24:12.513    4939-4939/com.bbbb.example.maps E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.bbbb.example.maps, PID: 4939
    java.lang.IllegalArgumentException: width and height must be > 0
            at android.graphics.Bitmap.createBitmap(Bitmap.java:807)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:786)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:718)
            at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:594)
            at org.osmdroid.bonuspack.kml.IconStyle.getFinalIcon(IconStyle.java:79)
            at org.osmdroid.bonuspack.kml.IconStyle.styleMarker(IconStyle.java:89)
            at org.osmdroid.bonuspack.kml.KmlPoint.applyDefaultStyling(KmlPoint.java:73)
            at org.osmdroid.bonuspack.kml.KmlPoint.buildOverlay(KmlPoint.java:94)
            at org.osmdroid.bonuspack.kml.KmlPlacemark.buildOverlay(KmlPlacemark.java:124)
            at org.osmdroid.bonuspack.kml.KmlFolder.buildOverlay(KmlFolder.java:160)
            at org.osmdroid.bonuspack.kml.KmlFolder.buildOverlay(KmlFolder.java:160)
            at com.bbbb.example.maps.MapsActivity.updateKML(MapsActivity.java:1829)
            at com.bbbb.example.maps.MapsActivity.access$000(MapsActivity.java:55)
            at com.bbbb.example.maps.MapsActivity$putKML.onPostExecute(MapsActivity.java:1813)
            at com.bbbb.example.maps.MapsActivity$putKML.onPostExecute(MapsActivity.java:1776)
            at android.os.AsyncTask.finish(AsyncTask.java:632)
            at android.os.AsyncTask.access$600(AsyncTask.java:177)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5114)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by MKergall** [comment]
Oh, yes - I see: you got an issue related to IconStyle hotspot in Google Maps. 

The source code fix of this issue has been commited last july. But the OSMBonusPack lib including this fix has still not been released yet. 
I will release it ASAP. 
In the meantime, if you can build the lib yourself, this should solve the issue.

**Comment by MKergall** [comment]
OSMBonusPack v5.4 just released, fixing the issue.

**Comment by blanml** [comment]
Thank you very much! The new version of OSMBonusPack fixes the issue! And thanks a lot for the quick solution!!!

**Comment by 835700012** [comment]
[kmlfile(change extenion txt to kml).txt](https://github.com/MKergall/osmbonuspack/files/1552432/kmlfile.change.extenion.txt.to.kml.txt)
HI,May I have a question?
could u please be so kind to test this kml file ?
I can not load the kml [file.](url)
