### ISSUE TITLE
Can't get Real Path between two points , I got a direct line 

### ISSUE THREAD

**Issue by anasquedan** [MKergall/osmbonuspack#218]
Dear there,
I Can't get Real Path between two points , I got a direct line between them, here is my sample code, 
I put that code under onCreate method , also I tried to handle it by runnable but without getting a worth result , just a direct line between two points 
GeoPoint startPoint = new GeoPoint(48.2,-1.88) ; 
 RoadManager roadManager = new OSRMRoadManager();
ArrayList<GeoPoint> waypoints = new ArrayList<GeoPoint>(); 
waypoints.add(startPoint); GeoPoint endPoint = new GeoPoint(48.4, -1.9); 
waypoints.add(endPoint);
Road road = roadManager.getRoad(waypoints);
Polyline roadOverlay = RoadManager.buildRoadOverlay(road, this);
map.getOverlays().add(roadOverlay);
map.invalidate();

Any advice, suggestions or help ?

**Comment by MKergall** [comment]
Have a look here: 
http://stackoverflow.com/questions/21213224/roadmanager-for-osmdroid-error/21894178#21894178

**Comment by anasquedan** [comment]
Here is the log cat which I got @MKergall :
 ```
04-15 16:55:16.782 9379-9379/com.android.application.osm I/RoadManager: org.osmdroid.bonuspack.routing.OSRMRoadManager@62b434e
04-15 16:55:16.782 9379-9379/com.android.application.osm D/BONUSPACK: OSRMRoadManager.getRoad:http://router.project-osrm.org/viaroute?&loc=48.129999999999995,-1.63&loc=48.12,-1.5&instructions=true&alt=false
04-15 16:55:16.790 9379-9379/com.android.application.osm W/System.err:     at org.osmdroid.bonuspack.routing.OSRMRoadManager.getRoad(OSRMRoadManager.java:205)
04-15 16:55:16.791 9379-9379/com.android.application.osm E/BONUSPACK: OSRMRoadManager::getRoad: request failed.

04-15 16:58:24.317 16801-16801/com.android.application.osm I/RoadManager: org.osmdroid.bonuspack.routing.OSRMRoadManager@15739d7c
04-15 16:58:24.317 16801-16801/com.android.application.osm D/BONUSPACK: OSRMRoadManager.getRoad:http://router.project-osrm.org/viaroute?&loc=48.129999999999995,-1.63&loc=48.12,-1.5&instructions=true&alt=false
04-15 16:58:24.331 16801-16801/com.android.application.osm W/System.err:     at org.osmdroid.bonuspack.routing.OSRMRoadManager.getRoad(OSRMRoadManager.java:205)
04-15 16:58:24.331 16801-16801/com.android.application.osm E/BONUSPACK: OSRMRoadManager::getRoad: request failed.
```
I used osmbonuspack 5.1 , and the osmdroid is 4.2 ? any suggestions ?

**Comment by anasquedan** [comment]
OSRMRoadManager::getRoad: request failed.

**Comment by anasquedan** [comment]
Here is another log after putting strictMode.ThreadPolicy() 

> ```

> 04-15 19:22:11.490 9353-9353/com.android.application.osm D/BONUSPACK: OSRMRoadManager.getRoad - finished
> 04-15 19:22:11.494 9353-9353/com.android.application.osm I/RoadManager: org.osmdroid.bonuspack.routing.OSRMRoadManager@62b434e
> 04-15 19:22:11.513 9353-9527/com.android.application.osm D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
> 04-15 19:22:11.518 9353-9353/com.android.application.osm D/Atlas: Validating map...
> 04-15 19:22:11.543 9353-9527/com.android.application.osm I/Adreno-EGL: <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.BF.1.1.1_RB1.05.01.00.042.030_msm8974_LA.BF.1.1.1_RB1__release_AU ()
>                                                                        OpenGL ES Shader Compiler Version: E031.25.03.06
>                                                                        Build Date: 07/13/15 Mon
>                                                                        Local Branch: mybranch11906725
>                                                                        Remote Branch: quic/LA.BF.1.1.1_rb1.26
>                                                                        Local Patches: NONE
>                                                                        Reconstruct Branch: AU_LINUX_ANDROID_LA.BF.1.1.1_RB1.05.01.00.042.030 + 6151be1 + a1e0343 + 002d7d6 + 7d0e3f7 +  NOTHING
> 04-15 19:22:11.543 9353-9527/com.android.application.osm I/OpenGLRenderer: Initialized EGL, version 1.4
> 04-15 19:22:11.559 9353-9527/com.android.application.osm D/OpenGLRenderer: Enabling debug mode 0
> 04-15 19:22:11.585 9353-9353/com.android.application.osm I/org.osmdroid.tileprovider.LRUMapTileCache: Tile cache increased from 9 to 48
> 04-15 19:22:11.693 9353-9353/com.android.application.osm W/IInputConnectionWrapper: showStatusIcon on inactive InputConnection
> 04-15 19:22:11.726 9353-9353/com.android.application.osm I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@2b419c6f time:68935457
> 04-15 19:22:17.691 9353-9353/com.android.application.osm I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@2b419c6f time:68941422
> 04-15 19:22:18.512 9353-9353/com.android.application.osm I/org.osmdroid.tileprovider.LRUMapTileCache: Tile cache increased from 48 to 63
> 04-15 19:22:19.593 9353-9353/com.android.application.osm I/org.osmdroid.tileprovider.MapTileProviderBase: rescale tile cache from 17 to 16
> 04-15 19:22:19.718 9353-9353/com.android.application.osm I/org.osmdroid.tileprovider.MapTileProviderBase: Finished rescale in 125ms
> 04-15 19:22:20.650 9353-9353/com.android.application.osm I/org.osmdroid.tileprovider.MapTileProviderBase: rescale tile cache from 16 to 17
> 04-15 19:22:20.895 9353-9364/com.android.application.osm W/art: Suspending all threads took: 6.313ms
> 04-15 19:22:20.912 9353-9353/com.android.application.osm I/org.osmdroid.tileprovider.MapTileProviderBase: Finished rescale in 262ms
> 04-15 19:22:21.464 9353-9353/com.android.application.osm I/org.osmdroid.tileprovider.MapTileProviderBase: rescale tile cache from 17 to 18
> 04-15 19:22:21.647 9353-9353/com.android.application.osm I/org.osmdroid.tileprovider.MapTileProviderBase: Finished rescale in 183ms
> 04-15 19:22:29.447 10464-10464/com.android.application.osm I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@2b419c6f time:68953177
> 04-15 19:23:12.809 11197-11197/com.android.application.osm I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@2b419c6f time:68996539
> 04-15 19:25:22.962 11197-11197/com.android.application.osm I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@2b419c6f time:69126692
```

**Comment by MKergall** [comment]
1) The versions you use are obsolete. Use latest releases. 
2) When setting strictMode.ThreadPolicy(), is your code now working? I cannot guess from your logcat extract, as it starts when getRoad finishes.

**Comment by anasquedan** [comment]
I used the latest one , and no its not ... It doesn't work until now , just its a straight line. .can I contact you to see this issue directly if that's possible.

**Comment by anasquedan** [comment]
Here is the full log : 

```
0:05.680 1814-1814/com.android.application.osm W/System: ClassLoader referenced unknown path: /data/app/com.android.application.osm-1/lib/x86
04-17 06:50:08.554 1814-1814/com.android.application.osm W/System: ClassLoader referenced unknown path: /data/app/com.android.application.osm-1/lib/x86
04-17 06:50:08.584 1814-1814/com.android.application.osm I/org.osmdroid.views.MapView: Using tile source: org.osmdroid.tileprovider.tilesource.XYTileSource@7a76747
04-17 06:50:08.592 1814-1814/com.android.application.osm I/org.osmdroid.tileprovider.modules.MapTileFileStorageProviderBase: sdcard state: mounted
04-17 06:50:08.596 1814-1814/com.android.application.osm I/org.osmdroid.tileprovider.modules.MapTileFileStorageProviderBase: sdcard state: mounted
04-17 06:50:08.625 1814-1814/com.android.application.osm I/org.osmdroid.tileprovider.MapTileProviderBase: rescale tile cache from 0 to 17
04-17 06:50:08.627 1814-1814/com.android.application.osm I/org.osmdroid.tileprovider.MapTileProviderBase: Finished rescale in 2ms
04-17 06:50:08.635 1814-1814/com.android.application.osm D/BONUSPACK: OSRMRoadManager.getRoad:http://router.project-osrm.org/viaroute?&loc=32.014435,35.871449999999996&loc=32.007793,35.875918&instructions=true&alt=false
04-17 06:50:09.511 1814-1814/com.android.application.osm D/BONUSPACK: OSRMRoadManager.getRoad - finished
04-17 06:50:09.512 1814-1814/com.android.application.osm I/RoadManager: org.osmdroid.bonuspack.routing.OSRMRoadManager@9f64d28
04-17 06:50:09.519 1814-2057/com.android.application.osm D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
                                                                           
                                                                           [ 04-17 06:50:09.521  1814: 1814 D/         ]
                                                                           HostConnection::get() New Host Connection established 0xa9570e50, tid 1814
04-17 06:50:09.557 1814-2057/com.android.application.osm D/libEGL: loaded /system/lib/egl/libEGL_emulation.so
04-17 06:50:09.559 1814-2057/com.android.application.osm D/libEGL: loaded /system/lib/egl/libGLESv1_CM_emulation.so
04-17 06:50:09.564 1814-2057/com.android.application.osm D/libEGL: loaded /system/lib/egl/libGLESv2_emulation.so
                                                                   
                                                                   [ 04-17 06:50:09.570  1814: 2057 D/         ]
                                                                   HostConnection::get() New Host Connection established 0xa9570f20, tid 2057
04-17 06:50:09.604 1814-2057/com.android.application.osm I/OpenGLRenderer: Initialized EGL, version 1.4
04-17 06:50:09.697 1814-2057/com.android.application.osm W/EGL_emulation: eglSurfaceAttrib not implemented
04-17 06:50:09.697 1814-2057/com.android.application.osm W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xa227ffe0, error=EGL_SUCCESS
04-17 06:50:09.738 1814-1814/com.android.application.osm I/org.osmdroid.tileprovider.LRUMapTileCache: Tile cache increased from 9 to 54
04-17 06:53:04.079 7228-7228/com.android.application.osm W/System: ClassLoader referenced unknown path: /data/app/com.android.application.osm-1/lib/x86
04-17 06:53:04.576 7228-7228/com.android.application.osm W/System: ClassLoader referenced unknown path: /data/app/com.android.application.osm-1/lib/x86
04-17 06:53:04.715 7228-7228/com.android.application.osm I/org.osmdroid.views.MapView: Using tile source: org.osmdroid.tileprovider.tilesource.XYTileSource@2cdb15a
04-17 06:53:04.725 7228-7228/com.android.application.osm I/org.osmdroid.tileprovider.modules.MapTileFileStorageProviderBase: sdcard state: mounted
04-17 06:53:04.733 7228-7228/com.android.application.osm I/org.osmdroid.tileprovider.modules.MapTileFileStorageProviderBase: sdcard state: mounted
04-17 06:53:04.780 7228-7228/com.android.application.osm I/org.osmdroid.tileprovider.MapTileProviderBase: rescale tile cache from 0 to 17
04-17 06:53:04.782 7228-7228/com.android.application.osm I/org.osmdroid.tileprovider.MapTileProviderBase: Finished rescale in 2ms
04-17 06:53:05.002 7228-7238/com.android.application.osm I/art: Background partial concurrent mark sweep GC freed 2042(492KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 1809KB/2MB, paused 4.775ms total 239.093ms
04-17 06:53:05.006 7228-7228/com.android.application.osm W/art: Verification of org.osmdroid.bonuspack.routing.Road org.osmdroid.bonuspack.routing.OSRMRoadManager.getRoad(java.util.ArrayList) took 186.517ms
04-17 06:53:05.018 7228-7228/com.android.application.osm D/BONUSPACK: OSRMRoadManager.getRoad:http://router.project-osrm.org/viaroute?&loc=32.014435,35.871449999999996&loc=32.007793,35.875918&instructions=true&alt=false
04-17 06:53:05.693 7228-7234/com.android.application.osm W/art: Suspending all threads took: 50.462ms
04-17 06:53:05.943 7228-7228/com.android.application.osm D/BONUSPACK: OSRMRoadManager.getRoad - finished
04-17 06:53:05.952 7228-7228/com.android.application.osm I/RoadManager: org.osmdroid.bonuspack.routing.OSRMRoadManager@9f64d28
04-17 06:53:05.960 7228-7317/com.android.application.osm D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
                                                                           
                                                                           [ 04-17 06:53:05.965  7228: 7228 D/         ]
                                                                           HostConnection::get() New Host Connection established 0xa9570b00, tid 7228
04-17 06:53:06.044 7228-7317/com.android.application.osm D/libEGL: loaded /system/lib/egl/libEGL_emulation.so
04-17 06:53:06.045 7228-7317/com.android.application.osm D/libEGL: loaded /system/lib/egl/libGLESv1_CM_emulation.so
04-17 06:53:06.052 7228-7317/com.android.application.osm D/libEGL: loaded /system/lib/egl/libGLESv2_emulation.so
                                                                   
                                                                   [ 04-17 06:53:06.059  7228: 7317 D/         ]
                                                                   HostConnection::get() New Host Connection established 0xaec92bf0, tid 7317
04-17 06:53:06.098 7228-7317/com.android.application.osm I/OpenGLRenderer: Initialized EGL, version 1.4
04-17 06:53:06.300 7228-7317/com.android.application.osm W/EGL_emulation: eglSurfaceAttrib not implemented
04-17 06:53:06.300 7228-7317/com.android.application.osm W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xab17a560, error=EGL_SUCCESS
04-17 06:53:06.366 7228-7228/com.android.application.osm I/org.osmdroid.tileprovider.LRUMapTileCache: Tile cache increased from 9 to 54
04-17 06:53:07.374 7228-7238/com.android.application.osm W/art: Suspending all threads took: 11.684ms
```

**Comment by anasquedan** [comment]
@MKergall when I tried to get mStatus by using :: Log.i("RoadManager", String.valueOf(road.mStatus)); . 
I got 200 , any suggestions or help , the same code was working previously and without doing any modification now its failed to route between two points

**Comment by anasquedan** [comment]
@MKergall I need to get the solution as soon as possible am working on that map.
After investigation the issue occurred here as the jString is null and I got the log message , how to fix that error , can you help me please
```
 String jString = connection.getContentAsString();
        connection.close();
        if(jString == null) {
            Log.e("BONUSPACK", "OSRMRoadManager::getRoad: request failed.");
```

**Comment by MKergall** [comment]
1) Which versions of OSMBonusPack and osmdroid are you using EXACTLY? 

2) Just above, you write that you get the log message due to jString == null. But your latest full logcat doesn't contain this log message ("OSRMRoadManager::getRoad: request failed.")! So why do you think that jString is null? 

3) You write your road.mStatus value is 200. This is hardly believable, as 1) jString is null and 2) nowhere in the code the json status is copied in road.mStatus. 

To progress, please provide:
- your latest code, including strictMode.ThreadPolicy() and Logging of road.mStatus
- the corresponding logcat.

**Comment by masztalski** [comment]
Hi, I discovered today this issue. According to my small research OSRM changed their API:
Here is my full logcat
```
04-28 15:16:51.102 11036-12066/com.*** D/BONUSPACK: OSRMRoadManager.getRoads:http://router.project-osrm.org/viaroute?&loc=51.128792999999995,17.04541&loc=51.076912,17.018243&instructions=true&alt=false&z=14
04-28 15:16:51.111 11036-11036/com.*** I/OsmDroid: Tile cache increased from 9 to 12
04-28 15:16:51.314 11036-12066/com.*** D/libc-netbsd: getaddrinfo: router.project-osrm.org get result from proxy >>
04-28 15:16:51.323 11036-12066/com.*** D/Posix: [Posix_connect Debug]Process com.*** :80 
04-28 15:17:01.472 11036-12066/com.*** W/System.err: java.net.SocketTimeoutException
04-28 15:17:01.481 11036-12066/com.*** W/System.err:     at java.net.PlainSocketImpl.read(PlainSocketImpl.java:511)
04-28 15:17:01.481 11036-12066/com.*** W/System.err:     at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
04-28 15:17:01.481 11036-12066/com.*** W/System.err:     at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
04-28 15:17:01.481 11036-12066/com.*** W/System.err:     at okio.Okio$2.read(Okio.java:139)
04-28 15:17:01.482 11036-12066/com.*** W/System.err:     at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
04-28 15:17:01.482 11036-12066/com.*** W/System.err:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
04-28 15:17:01.482 11036-12066/com.*** W/System.err:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
04-28 15:17:01.482 11036-12066/com.*** W/System.err:     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
04-28 15:17:01.482 11036-12066/com.*** W/System.err:     at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
04-28 15:17:01.483 11036-12066/com.*** W/System.err:     at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:79)
04-28 15:17:01.483 11036-12066/com.*** W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:909)
04-28 15:17:01.483 11036-12066/com.*** W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.access$300(HttpEngine.java:93)
04-28 15:17:01.483 11036-12066/com.*** W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:894)
04-28 15:17:01.484 11036-12066/com.*** W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:748)
04-28 15:17:01.484 11036-12066/com.*** W/System.err:     at com.squareup.okhttp.Call.getResponse(Call.java:277)
04-28 15:17:01.484 11036-12066/com.*** W/System.err:     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:234)
04-28 15:17:01.484 11036-12066/com.*** W/System.err:     at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:196)
04-28 15:17:01.485 11036-12066/com.*** W/System.err:     at com.squareup.okhttp.Call.execute(Call.java:79)
04-28 15:17:01.485 11036-12066/com.*** W/System.err:     at org.osmdroid.bonuspack.utils.HttpConnection.doGet(HttpConnection.java:62)
04-28 15:17:01.485 11036-12066/com.*** W/System.err:     at org.osmdroid.bonuspack.utils.BonusPackHelper.requestStringFromUrl(BonusPackHelper.java:74)
04-28 15:17:01.485 11036-12066/com.*** W/System.err:     at org.osmdroid.bonuspack.routing.OSRMRoadManager.getRoads(OSRMRoadManager.java:178)
04-28 15:17:01.485 11036-12066/com.*** W/System.err:     at org.osmdroid.bonuspack.routing.OSRMRoadManager.getRoad(OSRMRoadManager.java:243)
04-28 15:17:01.486 11036-12066/com.*** W/System.err:     at com.impelit.mcrm2.utils.maputils.MapUtils.getRoad(MapUtils.java:136)
04-28 15:17:01.486 11036-12066/com.*** W/System.err:     at com.impelit.mcrm2.utils.maputils.MapUtils.lambda$setMap$17(MapUtils.java:98)
04-28 15:17:01.486 11036-12066/com.*** W/System.err:     at com.impelit.mcrm2.utils.maputils.MapUtils.access$lambda$5(MapUtils.java)
04-28 15:17:01.486 11036-12066/com.*** W/System.err:     at com.impelit.mcrm2.utils.maputils.MapUtils$$Lambda$9.call(Unknown Source)
04-28 15:17:01.487 11036-12066/com.*** W/System.err:     at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:32)
04-28 15:17:01.487 11036-12066/com.*** W/System.err:     at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:17)
04-28 15:17:01.487 11036-12066/com.*** W/System.err:     at rx.Observable$2.call(Observable.java:162)
04-28 15:17:01.488 11036-12066/com.*** W/System.err:     at rx.Observable$2.call(Observable.java:154)
04-28 15:17:01.488 11036-12066/com.*** W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:8314)
04-28 15:17:01.488 11036-12066/com.*** W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
04-28 15:17:01.488 11036-12066/com.*** W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
04-28 15:17:01.488 11036-12066/com.*** W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
04-28 15:17:01.489 11036-12066/com.*** W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-28 15:17:01.489 11036-12066/com.*** W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
04-28 15:17:01.489 11036-12066/com.*** W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
04-28 15:17:01.489 11036-12066/com.*** W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-28 15:17:01.490 11036-12066/com.*** W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-28 15:17:01.490 11036-12066/com.*** W/System.err:     at java.lang.Thread.run(Thread.java:841)
04-28 15:17:01.490 11036-12066/com.*** E/BONUSPACK: OSRMRoadManager::getRoad: request failed.
```

**Comment by MKergall** [comment]
@masztalski 

OSRM is deploying a new API, but on 28/4/16, their previous API is still accessible => I just tried the request from your logcat: 
http://router.project-osrm.org/viaroute?&loc=51.128792999999995,17.04541&loc=51.076912,17.018243&instructions=true&alt=false&z=14

It returns a valid result. 

You just got a timeout. Could be a temporary issue on the server. Try again.
