### ISSUE TITLE
RoadManager error

### ISSUE THREAD

**Issue by Ewrei** [MKergall/osmbonuspack#277]
You can not build a route. The request is sent. Here you can see the result

http://open.mapquestapi.com/guidance/v1/route?key=7Qr7HWzQEtrU9HV0Qs4GxwAoYho4vGbI&from=52.1149723,23.7434935&to=52.106622,23.690805&outFormat=xml&shapeFormat=cmp&narrativeType=text&unit=k&fishbone=false&routeType=bicycle

indicates that line.
Road road = roadManager.getRoad(waypoints);

       

        RoadManager roadManager = new MapQuestRoadManager("7Qr7HWzQEtrU9HV0Qs4GxwAoYho4vGbI");
        roadManager.addRequestOption("routeType=bicycle");

        ArrayList<GeoPoint> waypoints = new ArrayList<GeoPoint>();
        waypoints.add(startPoint);
        GeoPoint endPoint = new GeoPoint(52.106622, 23.690805);
        waypoints.add(endPoint);

        Road road = roadManager.getRoad(waypoints);
        Polyline roadOverlay = RoadManager.buildRoadOverlay(road);
        m_mapView.getOverlays().add(roadOverlay);
        m_mapView.invalidate();

Error

D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.ewrei.osmtest2, PID: 8544
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.ewrei.osmtest2/com.example.ewrei.osmtest2.MainActivity}: android.os.NetworkOnMainThreadException
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2320)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2380)
                      at android.app.ActivityThread.access$800(ActivityThread.java:151)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1285)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5289)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
                   Caused by: android.os.NetworkOnMainThreadException
                      at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
                      at java.net.InetAddress.lookupHostByName(InetAddress.java:418)
                      at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
                      at java.net.InetAddress.getAllByName(InetAddress.java:215)
                      at okhttp3.Dns$1.lookup(Dns.java:39)
                      at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:172)
                      at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:138)
                      at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:80)
                      at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:178)
                      at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
                      at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
                      at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                      at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                      at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                      at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                      at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
                      at okhttp3.RealCall.execute(RealCall.java:60)
                      at org.osmdroid.bonuspack.utils.HttpConnection.doGet(HttpConnection.java:68)
                      at org.osmdroid.bonuspack.routing.MapQuestRoadManager.getRoad(MapQuestRoadManager.java:88)
                      at com.example.ewrei.osmtest2.MainActivity.onCreate(MainActivity.java:91)
                      at android.app.Activity.performCreate(Activity.java:6018)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2273)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2380) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1285) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:135) 
                      at android.app.ActivityThread.main(ActivityThread.java:5289) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
I/Process: Sending signal. PID: 8544 SIG: 9
Application terminated.

**Comment by MKergall** [comment]
see here: http://stackoverflow.com/questions/21213224/roadmanager-for-osmdroid-error

**Comment by saurabhomer258** [comment]
try out this code:
@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState); 
    setContentView(R.layout.activity_main);       
    StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();
    StrictMode.setThreadPolicy(policy);
}
