### ISSUE TITLE
parsurlkml

### ISSUE THREAD

**Issue by zzahira** [MKergall/osmbonuspack#284]
When i try to parse kml url by :
 Boolean ok=mKmlDocument.parseKMLUrl(url);
i have stopped by this issues:
FATAL EXCEPTION: main
                                                                              Process: com.example.zahira.mapquest_, PID: 27134
                                                                              java.lang.IllegalStateException: Could not execute method for android:onClick
                                                                                  at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:293)
                                                                                  at android.view.View.performClick(View.java:5246)
                                                                                  at android.widget.TextView.performClick(TextView.java:10602)
                                                                                  at android.view.View$PerformClick.run(View.java:21256)
                                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:145)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6917)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
                                                                               Caused by: java.lang.reflect.InvocationTargetException
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
                                                                                  at android.view.View.performClick(View.java:5246) 
                                                                                  at android.widget.TextView.performClick(TextView.java:10602) 
                                                                                  at android.view.View$PerformClick.run(View.java:21256) 
                                                                                  at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                  at android.os.Looper.loop(Looper.java:145) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6917) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
                                                                               Caused by: android.os.NetworkOnMainThreadException
                                                                                  at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
                                                                                  at java.net.InetAddress.lookupHostByName(InetAddress.java:418)
                                                                                  at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)

I can't understand the source of problem.
Thank you for advanced.

**Comment by spyhunter99** [comment]
`Caused by: android.os.NetworkOnMainThreadException`

that's your problem. I'm pretty sure there are notes about this on the wiki

**Comment by spyhunter99** [comment]
https://github.com/MKergall/osmbonuspack/wiki/Tutorial_0#important-note-about-network-calls

**Comment by zzahira** [comment]
thank you,i will try it.

**Comment by zzahira** [comment]
Now it's work fine, please i have a question ,i want to make apps for poi but i need more information for example number phone and email,i throught to use my own data and display it as layer with kml format,but i don't know if can i fetch in kml or i must work with json file. i hope that i good formed my question.Thank you very much for advanced.

**Comment by MKergall** [comment]
Submit requests for help on StackOverflow please.

**Comment by zzahira** [comment]
thank you very mutch ,i have use overpass api by your api osmbonuspack,i found that i can get all information about POI if it's already exist, now i'm wondering if i can get result of  query overpassProvider.urlForTagSearchKml in json object for direct access to data. and really i don't know how can i compensate you ,this api help me a lot of,thank you very mcuh

**Comment by MKergall** [comment]
Thanks for the feedback. 
Yes, with overpassProvider.urlForTagSearchKml you will have direct access to data, loaded as [KML objects](https://github.com/MKergall/osmbonuspack/wiki/KML).
