### ISSUE TITLE
Cannot download OSM tile using CacheManager

### ISSUE THREAD

**Issue by m91snik** [MKergall/osmbonuspack#390]
Standard OSM map TileSourceFactory.MAPNIK cannot be downloaded using cache manager.

This part
```
CacheManager cacheManager = new CacheManager(map);
int zoomMin = map.getZoomLevel();
int zoomMax = map.getZoomLevel()+4;
cacheManager.downloadAreaAsync(this, map.getBoundingBox(), zoomMin, zoomMax);
```

 throws exception

```
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
    Process: com.osmnavigator, PID: 14818
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: org.osmdroid.tileprovider.tilesource.TileSourcePolicyException: This online tile source doesn't support bulk download
        at org.osmdroid.tileprovider.cachemanager.CacheManager$3.preCheck(CacheManager.java:843)
        at org.osmdroid.tileprovider.cachemanager.CacheManager$CacheManagerTask.doInBackground(CacheManager.java:739)
        at org.osmdroid.tileprovider.cachemanager.CacheManager$CacheManagerTask.doInBackground(CacheManager.java:644)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
```

Pls note that version from play market works fine, but version from github from this revision d02be87a513b638f20db6f0fbe174d5547987b65 has this issue.

**Comment by MKergall** [comment]
Cache manager code has been moved to osmdroid => please raise the ticket in osmdroid repo.
