### ISSUE TITLE
Issue with KML file 

### ISSUE THREAD

**Issue by StoreExecution** [MKergall/osmbonuspack#397]
Hi, 
i have a error with a KML the app crashes , i'am making KML files from google earth until now they all work , except this one can you tell me what causing the crash i tried to open it on web kml views and it worked well . 

```
0-12-22 15:10:57.010 31033-31033/com.app.test E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.app.test PID: 31033
    java.lang.StackOverflowError: stack size 8MB
        at org.osmdroid.util.BoundingBox.set(BoundingBox.java:65)
        at org.osmdroid.util.BoundingBox.<init>(BoundingBox.java:43)
        at org.osmdroid.views.overlay.Overlay.<init>(Overlay.java:57)
        at org.osmdroid.views.overlay.FolderOverlay.<init>(FolderOverlay.java:32)
        at org.osmdroid.bonuspack.kml.KmlFolder.buildOverlay(KmlFolder.java:178)
        at org.osmdroid.bonuspack.kml.KmlFolder.buildOverlay(KmlFolder.java:182)
        at org.osmdroid.bonuspack.kml.KmlFolder.buildOverlay(KmlFolder.java:182)
        at org.osmdroid.bonuspack.kml.KmlFolder.buildOverlay(KmlFolder.java:182)
        at org.osmdroid.bonuspack.kml.KmlFolder.buildOverlay(KmlFolder.java:182)
......
AndroidRuntime: at org.osmdroid.bonuspack.kml.KmlFolder.buildOverlay(KmlFolder.java:182)
```

file : 
[sector.kml.zip](https://github.com/MKergall/osmbonuspack/files/5730315/sector.kml.zip)

**Comment by MKergall** [comment]
Root cause: in your file, you have a PlaceMark containing a Document: 
		<Document>
			<name>22.12.2020 SECT 2.kml</name>
			<open>1</open>
		</Document>

This is quite weird - I'm surprised that could be a valid KML structure. Did you really produced this file straight from Google Earth? 
This case is not properly handled by the lib: it causes an infinite recursive loop. 

Remove this section in your file and it will be fine.

**Comment by StoreExecution** [comment]
> Root cause: in your file, you have a PlaceMark containing a Document:
> 
> ```
> 		<Document>
> 			<name>22.12.2020 SECT 2.kml</name>
> 			<open>1</open>
> 		</Document>
> ```
> 
> This is quite weird - I'm surprised that could be a valid KML structure. Did you really produced this file straight from Google Earth?
> This case is not properly handled by the lib: it causes an infinite recursive loop.
> 
> Remove this section in your file and it will be fine.

yes it was directly exported from google earth but i did not experience this issue since then .
