### ISSUE TITLE
App Crashes when using BingMapTiles offline

### ISSUE THREAD

**Issue by StoreExecution** [MKergall/osmbonuspack#429]
Hi,
So. , I have this issue when using Bing tiles (BingMapTileSource.IMAGERYSET_AERIALWITHLABELS) and being offline (no internet ) the app crashes with the error below 

`
 E/AndroidRuntime: FATAL EXCEPTION: GarbageCollector
    Process:  xx, PID: 23818
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at java.util.Formatter.parse(Formatter.java:2545)
        at java.util.Formatter.format(Formatter.java:2504)
        at java.util.Formatter.format(Formatter.java:2458)
        at java.lang.String.format(String.java:2842)
        at org.osmdroid.tileprovider.tilesource.bing.BingMapTileSource.getTileURLString(BingMapTileSource.java:124)
        at org.osmdroid.tileprovider.modules.MapTileDownloader$TileLoader.loadTile(MapTileDownloader.java:188)
        at org.osmdroid.tileprovider.modules.MapTileModuleProviderBase$TileLoader.loadTileIfReachable(MapTileModuleProviderBase.java:213)
        at org.osmdroid.tileprovider.MapTilePreCache.search(MapTilePreCache.java:127)
        at org.osmdroid.tileprovider.MapTilePreCache.access$100(MapTilePreCache.java:31)
        at org.osmdroid.tileprovider.MapTilePreCache$1.run(MapTilePreCache.java:42)
        at org.osmdroid.util.GarbageCollector$1.run(GarbageCollector.java:32)
        at java.lang.Thread.run(Thread.java:764)
`

**Comment by MKergall** [comment]
Raise this issue in osmdroid project.
